### ISSUE TITLE
(Possibility to) hide version number on public page

### ISSUE THREAD

**Issue by codiflow** [tchapi/davis#101]
I think it would be better to hide the version number on the public davis page.
![grafik](https://github.com/tchapi/davis/assets/43847817/a6b42868-dd77-4fd5-a78e-a9acd91ca73d)

This makes it less attractive for bad people (and search engines) looking for not up-to-date installations. And the version number is displayed after login too so an admin can easily get it from there.

**Comment by tchapi** [comment]
Hello @codiflow 

Great suggestion! Would you be able to make a PR for this? It should be quite straightforward
