### ISSUE TITLE
doctrine:migrations:migrate error using version 1.4.9

### ISSUE THREAD

**Issue by tiiiecherle** [tchapi/davis#11]
Hey,

thanks for the update. When updating to version 1.4.9 `doctrine:migrations:migrate` outputs on a first run:
`[ERROR] The version "latest" couldn't be reached, there are no registered migrations.
`

On a second run the output is
`The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue.
`

After some research adding `?serverVersion=mariadb-10.5.5` to the database url the output is back to:
`[ERROR] The version "latest" couldn't be reached, there are no registered migrations.
`

Downgrading to version 1.4.8 outputs no errors and:
`No migrations to execute.`

I hope the database is still alright. Thanks for looking into it in advance.

**Comment by tchapi** [comment]
Hi
There are no migrations, so you shouldn't try to run it in the first place. The error message is not perfectly clear though, I guess they changed it with the version (see https://github.com/doctrine/migrations).

**Comment by tiiiecherle** [comment]
Hey,

thanks for the feedback.

1    When shall `doctrine:migrations:migrate` be run? 

2    Does `doctrine:migrations:migrate` have to be run on the first time the database is created? If yes, the same error described above occurs on a newly created database if I follow the readme.

3   Is it the new standard or a bug that `?serverVersion=mariadb-10.5.5` has to be added to the database url?

Thanks

**Comment by tchapi** [comment]
Hi

1. Never - it has changed in the new version of doctrine, I've just amended the README file to reflect this (I was using the migration cli but it was really just creating the schema), thanks for the heads up. So far, davis did not need migrations. Maybe in the future, and I'll add the relevant documentation if needed.
2. ↑
3. It's not compulsory since it's already indicated in the config. But if your server version is different than the one I indicated here: https://github.com/tchapi/davis/blob/b0694d60ac39a5a84124843c3a72ec93a7ded2da/config/packages/doctrine.yaml#L7 ... in this case you should indicate it in the `DATABASE_URL` config.

Best regards !

**Comment by tiiiecherle** [comment]
Hey,

thanks for the feedback.

1.   o.k., I will change my install/update script accordingly to skip this step. Thanks for updating the readme.

1.a    Is this the correct order of commands to create a new database?

- create user and new database with mysql commands, grant privileges

- customize .env file

- run `bin/console doctrine:schema:create`

1.b     Does `bin/console doctrine:schema:create` have to be changed if the database name is not davis?
1.c     Can `bin/console doctrine:schema:create` be run before customizing the .env file?

2.   o.k.
3.   Does this entry need to be the currently installed mariadb version? If yes, is there a way to use a variable for that or does it have to be updated on every mariadb update?
4.   After the errors I described in the issue how do I check if my database is ok and working correctly? There are no errors and the syncs seem to work fine.

Thanks

**Comment by tchapi** [comment]
Re,

1a — yes
1b — no, the name of the database is written in your `.env` file
1c — no (well, yes, but you will have an error saying that it can't find the database)
3 — I'll leave you to the doctrine documentation for that: https://symfony.com/doc/current/reference/configuration/doctrine.html I haven't delved too much into it
4 — Your database has not been modified, it's fine, don't worry.

**Comment by tiiiecherle** [comment]
Thanks ;)
