### ISSUE TITLE
LDAP password is logged in clear text

### ISSUE THREAD

**Issue by mpflanzer** [tchapi/davis#112]
Hi,

I spotted that (at least) if something goes wrong during the LDAP authentication the password appears in clear in the log file. E.g.

```
"file":"/var/www/davis/src/Services/LDAPAuth.php","line":164,"function":"flush","class":"ContainerYTqyTpY\\EntityManager_9a5be93","type":"->","args":[]},{"file":"/var/www/davis/src/Services/LDAPAuth.php","line":183,"function":"ldapOpen","class":"App\\Services\\LDAPAuth","type":"->","args":["moritz","MY_PASSWORD"]},{"file":"/var/www/davis/vendor/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php","line":103,"function":"validateUserPass","class":"App\\Services\\LDAPAuth","type":"->","args":["moritz","MY_PASSWORD"]}
```
If seen it also being logged as part of the `php-auth-pw` header.

Also the hashed password can appear in the log if something is going wrong on the database.

```
Integrity constraint violation: 1062 Duplicate entry 'moritz' for key 'UNIQ_1483A5E9F85E0677' at /var/www/davis/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:121)","INSERT INTO users (username, digesta1) VALUES (?, ?)",{"1":"moritz","2":"$2y$10$MY_PASSWORD_HASH"}
```

I have no experience with Symfony so I'm afraid I cannot really help with this. But I don't really feel comfortable using davis until this is addressed.

**Comment by tchapi** [comment]
Hi @mpflanzer 

Thanks, that's a good catch. Will see on how to filter them out

**Comment by tchapi** [comment]
Hi @mpflanzer 

I've added some circumventions in https://github.com/tchapi/davis/pull/116 — would you be so kind as to test your use cases and tell me if it's better?

Thanks a lot!

**Comment by mpflanzer** [comment]
Thanks, that's better for sure.

It still has the problem that *should* anything throw it would print the password. Do you know if there is a way to turn off printing the stack trace? I tried setting `APP_ENV=prod` and `APP_DEBUG=0` but I still see the full trace. :thinking:

**Comment by tchapi** [comment]
> should anything throw it would print the password

That's true, but it's also true for ~any other software that prints production logs to be honest :)

The real need in your case is to deactivate logs globally in production (_which is a very sane thing to do_) to mitigate that risk altogether. Traces are just logs with an "error" level, but TBH, passwords could as well creep in other levels (warnings, etc), so removing debug traces would not be a good solution.

Would you be interested in having a way to disable logging altogether with an env var?

**Comment by mpflanzer** [comment]
> Would you be interested in having a way to disable logging altogether with an env var?

That would make it a bit easier to deactivate them while still using the released docker image. If that's not a big change I think it would be nice. Otherwise rebuilding the docker image with a changed logger config is also not a disaster.

**Comment by tchapi** [comment]
Done [here](https://github.com/tchapi/davis/pull/116/files#r1378898704). If you confirm this is fine for you in your setup, I'll merge and provide a new release in the coming days

**Comment by mpflanzer** [comment]
:+1: for the FilterProcessor approach. That looks really nice. But for some reason it doesn't have any effect for me. For example if I throw an (invalid) exception in `ldapOpen` I still get this error log:

```
[2023-11-02T10:19:51.289613+01:00] app.ERROR: [500]: Error - Can only throw objects [{"file":"/var/www/davis/src/Services/LDAPAuth.php","line":189,"function":"ldapOpen","class":"App\\Services\\LDAPAuth","type":"->","args":["moritz","asdasda "]}
```

The `dav` function could be another candidate to redact the arguments:
```
{"file":"/var/www/davis/vendor/symfony/http-kernel/HttpKernel.php","line":163,"function":"dav","class":"App\\Controller\\DAVController","type":"->","args":[{"Symfony\\Component\\HttpFoundation\\Request":"PUT /dav/calendars/moritz/default HTTP/1.1\r\nAccept:          text/xml\r\nAccept-Charset:  utf-8,*;q=0.1\r\nAccept-Encoding: gzip, deflate, br\r\nAccept-Language: en-GB,en;q=0.5\r\nAuthorization:   Basic bW9yaXR6OmFzZGFzZGEg\r\nCache-Control:   no-cache\r\nConnection:      keep-alive\r\nContent-Length:  0\r\nContent-Type:    \r\nHost:            calendar.chickadee-engineering.com\r\nIf-Match:        nothing\r\nOrigin:          https://calendar.chickadee-engineering.com\r\nPhp-Auth-Pw:     asdasda \r\nPhp-Auth-User:   moritz\r\nPragma:          no-cache\r\nSec-Fetch-Dest:  empty\r\nSec-Fetch-Mode:  no-cors\r\nSec-Fetch-Site:  same-origin\r\nUser-Agent:      Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.3.1\r\nX-Php-Ob-Level:  0\r\n\r\n"},"calendars/moritz/default"]}
```

And with the latest commit I don't get any log file anymore. In the docker container the environment contains `LOG_FILE_PATH=%kernel.logs_dir%/%kernel.environment%.log` but there is never a file in `./var/log/prod.log`. If I take the commit before the log file appears as expected. :thinking:

Maybe it's just my setup that is somehow broken but could you double check that it's behaving as expected for you?

**Comment by tchapi** [comment]
> LOG_FILE_PATH=%kernel.logs_dir%/%kernel.environment%.log

You need to quote the path IMO, otherwise the variables are replaced sooner than expected

**Comment by tchapi** [comment]
> I still get this error log:

Are you in production mode? The change only applies there

> The dav function could be another candidate to redact the arguments

Will have a look!

**Comment by mpflanzer** [comment]
Yes, should be in production:

```
  davis:
    image: davis-dev
    #image: ghcr.io/tchapi/davis:v4.0.0
    environment:
      - APP_ENV=prod
      #- APP_DEBUG=0
      - LOG_FILE_PATH="%kernel.logs_dir%/%kernel.environment%.log"
```

Quoting the path (or not specifying anything) also doesn't help. No log file is generated with the latest commit

**Comment by tchapi** [comment]
Oh, gotcha, that's on me! Can you retry? I've pushed a fix (and added `dav` in the list of sensitive methods)

**Comment by mpflanzer** [comment]
Nice, the log file is now working. I still see the problem that the `args` are not redacted.

If instead of your loop I have the below it is working though. It's less generic than yours so I'm not super happy with it. I'll try to spend some more time with it to figure out the difference.  
```
        foreach ($record["context"] as $idx => $item) {
           foreach ($item as $key => $value) {
            if (self::PASSWORD_KEY === strtolower($key)) {
                $record["context"][$idx][$key] = '****';
            } elseif ('function' === strtolower($key)) {
                // Remove potentially sensitive data from function arguments
                if (in_array($value, self::SENSITIVE_ARGS_FUNCTIONS)) {
                    $record["context"][$idx]['args'] = ['****'];
                }
            } 
          }
        }
```

**Comment by tchapi** [comment]
Interesting, I didn't encounter this edge case when testing on my side. I've made the code a bit smarter in https://github.com/tchapi/davis/pull/116/commits/7084b9c42787d5229da327a539ccac0d633a56ed 🙏🏼

**Comment by mpflanzer** [comment]
LGTM, thanks for the effort.
