### ISSUE TITLE
Password storage for LDAP and IMAP login

### ISSUE THREAD

**Issue by mpflanzer** [tchapi/davis#113]
Hi,

is there a specific reason why with LDAP and IMAP authentication in combination with `AUTOCREATE` the actual password is stored in davis database?

Since in those cases the DB is not used for authentication couldn't the password be left empty or set to a random string?
https://github.com/tchapi/davis/blob/7de7098c57a2bce740deb941873991652e925262/src/Services/LDAPAuth.php#L161

That would reduce the risk of having it exposed in case of a security breach.

**Comment by tchapi** [comment]
Thanks! I've addressed it [here](https://github.com/tchapi/davis/pull/114), will test a bit more some edge cases before merging
