### ISSUE TITLE
sabre framework response with error 500 with PHP 8.2

### ISSUE THREAD

**Issue by thelittleblackbird** [tchapi/davis#115]
hi,

Recently i found that i get several errors 500 from the sabre framework.

The problem seems to be linked (if it is not identic) to this:
https://github.com/sabre-io/Baikal/issues/1154

coudl be possible to have a PHP downgrade until sabre fixs their codebase¿?

**Comment by tchapi** [comment]
I asked for a new release: https://github.com/sabre-io/dav/issues/1493 because it seems that their latest commit on master fixes the issue

**Comment by thelittleblackbird** [comment]
Thanks, then let's wait to Sabre maintainer answer

**Comment by tchapi** [comment]
Hi there,

4.5.0 is coming → https://github.com/sabre-io/dav/pull/1497 🎉 

Hopefully this will be available next week max so I can update the dependencies on Davis' side and make a release asap 🤞🏼

Thanks for your patience

**Comment by tchapi** [comment]
Just released https://github.com/tchapi/davis/releases/tag/v4.2.0 ✨

**Comment by thelittleblackbird** [comment]
thanks for your support

**Comment by thelittleblackbird** [comment]
dont want to ruin the current joy. But could it be possible that the sabre version is not update in the docker image?

i can still see a 4.4.0 in the compose.json from ghcr.io/tchapi/davis:v4.2.0 :)

**Comment by tchapi** [comment]
Just tested right now, it seems ok:

```
❯ docker run -it ghcr.io/tchapi/davis:v4.2.0 sh
/var/www/davis # cat composer.json | grep sabre
    "description": "A simple, fully translatable admin interface and frontend for sabre/dav based on Symfony",
        "sabre/dav": "^4.5.0",
```

Are you sure your container is updated to use the latest image?

**Comment by tchapi** [comment]
Hi @thelittleblackbird 👋🏼 

Did you finally make it work?

**Comment by thelittleblackbird** [comment]
hi

not really, still faces some issues that i dont know how to tackle.

small and stupid question, is there any way to enable a verbose log from all the framworks?

**Comment by tchapi** [comment]
> small and stupid question, is there any way to enable a verbose log from all the framworks?

You could set `APP_ENV=dev` in the environment to get more logs (in `var/log/dev.log`)

**Comment by tchapi** [comment]
Ah, yes, that's expected as you have a production container (that does not include the dev profiler that your app is trying to display here). So `APP_ENV=dev` in a production container is not really a good solution.

What are the remaining issues you are facing and trying to debug?
