### ISSUE TITLE
IMAP authentication

### ISSUE THREAD

**Issue by dominiquefournier** [tchapi/davis#12]
Hi !
Could you think to add more authentication scheme ? I am interested with IMAP auth, like describe in https://github.com/sabre-io/Baikal/pull/966

Thanks a lot !

**Comment by tchapi** [comment]
Hi @dominiquefournier 

Let me have a look at it. I don't have much time now, though, so if you could prime it with a PR, I'd be much obliged.

Thanks and best regards

**Comment by tchapi** [comment]
Ok, if I believe the PR you commented on, it's an easy endeavor;  Could you test the `feature/imap_auth` branch and tell me if everything is fine ?

See https://github.com/tchapi/davis/tree/feature/imap_auth

**Comment by dominiquefournier** [comment]
Yes ! Well done ! It works well ! Thank you so much !

**Comment by tchapi** [comment]
I'll merge this into the main branch, and make a specific release then

**Comment by tchapi** [comment]
See https://github.com/tchapi/davis/releases/tag/v1.5.0

**Comment by dominiquefournier** [comment]
Thanks a lot !
