### ISSUE TITLE
DAVx5 cannot connect a new account to v4.2.0

### ISSUE THREAD

**Issue by samwwwblack** [tchapi/davis#122]
Hi,

Connecting a new account via the DAVx5 android client to v4.2.0 returns an error that there are no CalDAV or CardDAV services on the given URL.

In the debug log from DAVx5 (sanitised and [attached](https://github.com/tchapi/davis/files/13416127/davx5.txt)) DAVx5 successfully gets the principal and `PROPFIND` for the user but davis returns an empty response to `OPTIONS`, which DAVx5 interprets as there being no service.

The v4.2.0 changeset introduced this empty response at [src/Controller/DAVController.php#L298-300](https://github.com/tchapi/davis/blob/a7d5b8a6fb2e439f3380d16223ddd1c956786088/src/Controller/DAVController.php#L298) - removing this allows DAVx5 to connect successfully.

I didn't run into this issue when connecting the user under Thunderbird, so I don't know if DAVx5 is doing something out of spec or Thunderbird is more tolerant of apparent errors.

**Comment by tiiiecherle** [comment]
Hey,

thanks for the new updates. I don't know if this is the same problem, but when using 4.2.0 or 4.2.1 macOS clients can no longer setup accounts in macOS that connect to davis. Old already established accounts keep on working, but new accounts can not be set up. Downgrading to davis 4.1.0 solves the issue.

And yes, I just tested, removing lines 298-300 solves the problem using davis 4.2.1.

Thanks @samwwwblack for tracking the issue down.

Thanks @tchapi for fixing in advance.

I think the issue is important to be fixed as new users or people that try davis would not be able to establish new client connects even with the correct settings.

**Comment by tchapi** [comment]
Hi 👋🏼 

Thanks for the reports — the empty OPTIONS response was introduced specifically for Thunderbird, to circumvent the fact that it was sending it without credentials in some cases (no auth set, for public calendars), leading to sabre/dav (the underlying lib) to deny access while it shouldn't.

> which DAVx5 interprets as there being no service.

This is weird though, as I don't think an OPTIONS should be used by DAVx5 (or even macOS) to decide on whether the _service is available_ or not (or actual user permissions?), since it's only used to know _which HTTP methods the API responds to_, but it should not bear the payload of the actual request.

I can remove the offending lines, but I'd like to try something before.

Can you modify the offending lines to:

```php
if ('OPTIONS' === $request->getMethod()) {
  $response = new Response();
  $response->headers->set('Allow', 'REPORT, PROPFIND, PROPPATCH, LOCK, UNLOCK, ACL, COPY, MOVE, MKCOL, CONNECT, DELETE, DONE, GET, HEAD, OPTIONS, PATCH, POST, PUT');
  return $response;
}

```

... and tell me if it works for your respective settings?

**Comment by tiiiecherle** [comment]
Hey @tchapi 

thanks again for the fast response.

I tried replacing

```
if ('OPTIONS' === $request->getMethod()) {
    return new Response();
}
```

with

```
if ('OPTIONS' === $request->getMethod()) {
  $response = new Response();
  $response->headers->set('Allow', 'REPORT, PROPFIND, PROPPATCH, LOCK, UNLOCK, ACL, COPY, MOVE, MKCOL, CONNECT, DELETE, DONE, GET, HEAD, OPTIONS, PATCH, POST, PUT');
  return $response;
}
```

and new connections from macOS clients are still not possible. So for me the change does not fix the issue.

If I just use Safari browser with the url

`MY_URL:443/dav`

I get a login prompt and I can successfully log in with both of the above codes and if the part of the code is deleted.

**Comment by tchapi** [comment]
Ok, thanks for trying the circumvention. I'd like to see the DavX behavior on this solution too to assess what these clients are trying to do with that OPTIONS request as it's still quite unclear to me

**Comment by tiiiecherle** [comment]
Ok, if you want me to test anything else I could do some more testing tomorrow.

**Comment by tchapi** [comment]
If I'm following the specs ([here](https://datatracker.ietf.org/doc/html/rfc4918) and [here](https://datatracker.ietf.org/doc/html/rfc4791)), this should work:

```php
if ('OPTIONS' === $request->getMethod()) {
    $response = new Response();
    $response->headers->add([
        'Allow' => 'OPTIONS, GET, HEAD, DELETE, PROPFIND, PUT, PROPPATCH, COPY, MOVE, REPORT',
        'DAV' => '1, 3, extended-mkcol, access-control, calendarserver-principal-property-search, resource-sharing, calendar-access, calendar-proxy, calendar-auto-schedule, calendar-availability, calendarserver-sharing, addressbook',
        'Ms-Author-Via' => 'DAV',
    ]);
    return $response;
}
```

It's a bit of a hack but I can refine later. Would you mind testing this version too by any chance 🙏🏼 ?

**Comment by samwwwblack** [comment]
Hi,

Sorry for the delay in responding.

Like @tiiiecherle , the initial patch didn't work, DAVx5 still failed with the same no service message.

The second patch allows DAVx5 to connect ([davx5.dav_header.txt](https://github.com/tchapi/davis/files/13418365/davx5.dav_header.txt)).

From DAVx5's source for this, it seems they are explicitly looking for [either `addressbook` or `calendar-access`](https://github.com/bitfireAT/davx5-ose/blob/fca6b5b89029f6d90d5c7de568edece9a3ecff2e/app/src/main/kotlin/at/bitfire/davdroid/servicedetection/DavResourceFinder.kt#L333) in the [`DAV` header in response to `OPTIONS`](https://github.com/bitfireAT/dav4jvm/blob/1ed89c165df47d9e7ff4c99974676c91d54697bf/src/main/kotlin/at/bitfire/dav4jvm/DavResource.kt#L144)

As an aside, I tried reconnecting Thunderbird with the patches and whilst it worked, I can see multiple 401 and 405 responses before it seems to actually try an authenticated request - I'll have a look and see if I can make sense of it.

Thank you for your quick work on this.

**Comment by samwwwblack** [comment]
I've played about with Thunderbird with a public calendar in a user account with the working patch and removing the empty response I get `Sabre\DAV\Exception\PreconditionFailed - An If-Match header was specified, but none of the specified ETags matched.`, where the `If-Match` header is `nothing` - oddly, in Thunderbird 115 at least, it logs that in response to a `PUT` request, not an `OPTIONS`.

The private calendar does get subscribed to, but not the public one - but if I add the public calendar directly, it appears OK.

Apologies, I may be drifting into another bug report here.

**Comment by tchapi** [comment]
This is very helpful, **thanks very much for your time**! I'll make another test with Thunderbird tomorrow as I think it's not really adhering to the standards here, and probably release 4.3 in the course of tomorrow with the patch

**Comment by tiiiecherle** [comment]
Hey,

@tchapi and @samwwwblack Thanks a lot to both of you.

I just tested the second patch and I can successfully add new accounts on macOS clients. 

Where is the party emoji when it's needed? ;)))

**Comment by tchapi** [comment]
The real fix (a bit more proper than hardcoding the values) is here: https://github.com/tchapi/davis/pull/124/files

**Comment by tiiiecherle** [comment]
The latest fix works for macOS clients.

**Comment by samwwwblack** [comment]
#124 Fixes the fault with DAVx5 and continues to work with Thunderbird, although I've not tested it with a public calendar.

**Comment by tchapi** [comment]
4.3.0 just [released](https://github.com/tchapi/davis/releases/tag/v4.3.0); I'll continue to iterate on the public calendars if needed but IMO the workaround is backwards compatible, so we should be fine

**Comment by tiiiecherle** [comment]
Thank you.

**Comment by tchapi** [comment]
I'm considering this as closed and will update if anything comes up (_especially related to the public calendars_). I'm restating my gratefulness for your thoughtful pointers and comprehensive bug reports.

And thank you for bearing with me while I fixed these issues 🙏🏼, I hope Davis suits your needs!
