### ISSUE TITLE
Recreate a deletet user: Internal server error

### ISSUE THREAD

**Issue by z3ky** [tchapi/davis#126]
Recreating a formerly deleted user ends up in: 500 Internal Server Error
Maybe its just a missing error message or is recreating a deleted user forbidden?

**Comment by tchapi** [comment]
Thanks for the report, I'll have a look soon. 
We don't "keep a reference" of deleted users, but we might have some rogue objects linked to it that doesn't get correctly deleted (it's my guess)

**Comment by tchapi** [comment]
Ok, after testing, I identified that the calendar proxies can remain in DB after deleting the user, I'm working on a fix

**Comment by tchapi** [comment]
Should be fixed by https://github.com/tchapi/davis/commit/93176d18d6ad67e846f3f264d29fba07e20e3728
