### ISSUE TITLE
WebProfilerBundle not found

### ISSUE THREAD

**Issue by holow29** [tchapi/davis#133]
Attempting to run sorely overdue migrations. Trying to follow the instructions for v3. When I run `bin/console doctrine:migrations:status`, I get the following error:

```
Symfony\Component\ErrorHandler\Error\ClassNotFoundError^ {#71
  #message: """
    Attempted to load class "WebProfilerBundle" from namespace "Symfony\Bundle\WebProfilerBundle".\n
    Did you forget a "use" statement for another namespace?
    """
  #code: 0
  #file: "./vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php"
  #line: 132
  trace: {
    ./vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php:132 { …}
    ./vendor/symfony/http-kernel/Kernel.php:386 { …}
    ./vendor/symfony/http-kernel/Kernel.php:788 { …}
    ./vendor/symfony/http-kernel/Kernel.php:128 { …}
    ./src/Kernel.php:16 {
      App\Kernel->boot(): void^
      › {
      ›     parent::boot();
      ›     $timezone = $this->getContainer()->getParameter('timezone');
    }
    ./vendor/symfony/framework-bundle/Console/Application.php:168 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:74 { …}
    ./vendor/symfony/console/Application.php:171 { …}
    ./bin/console:43 { …}
  }
}
2024-01-17T07:41:56+00:00 [critical] Uncaught Error: Class "Symfony\Bundle\WebProfilerBundle\WebProfilerBundle" not found

```

**Comment by tchapi** [comment]
Hi @holow29 👋🏼 

Are you running in `DEV` mode?

**Comment by holow29** [comment]
I have `APP_ENV=prod` set in fastcgi_param, and I also add `APP_ENV=prod` when I am executing the commands since I am using the docker container. Should I be using DEV? I am testing on the `edge` tag, which I know could be problematic.

**Comment by holow29** [comment]
Seems like the issue was my DATABASE_URL not being enclosed in quotes properly. The versioning with the "&" symbol seemed to be throwing things off.
(i.e.
`sudo docker exec -it davis sh -c "APP_ENV=prod DATABASE_URL=mysql://user:pass@mariadb:3306/davisdb?charset=utf8mb4&serverVersion=mariadb-11.2.2 bin/console doctrine:migrations:status"` = error
whereas
`sudo docker exec -it davis sh -c "APP_ENV=prod DATABASE_URL='mysql://user:pass@mariadb:3306/davisdb?charset=utf8mb4&serverVersion=mariadb-11.2.2' bin/console doctrine:migrations:status"` works.
Sorry for the issue, but appreciate the quick response!

**Comment by lgwapnitsky** [comment]
D'oh! :)
