### ISSUE TITLE
Cannot upgrade to version v4.4.1, parameter "timezone" must be defined

### ISSUE THREAD

**Issue by pacroix** [tchapi/davis#137]
Hello, I'm trying to upgrade my standalone installation (not docker) from v4.4.0 to v4.4.1.

I have added and set the new variables `APP_TIMEZONE="Europe/Berlin"` and `ADMIN_AUTH_BYPASS=false` in my `.env.local` file.
However when I try to run the application I get the following output:

```
$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating autoload files
115 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In App_KernelProdContainer.php line 819:
!!
!!    The parameter "timezone" must be defined.
!!
!!
!!
Script @auto-scripts was called via post-install-cmd
```

Exporting the configuration with `composer symfony:dump-env` didn't help with my issue. (I vaguely remember having to do that when I set up davis for the first time)

I have followed my procedure for upgrading, which has worked for all previous versions and this is the first time that it is failing. Is there something obvious I'm missing? For now I have rolled back to version v4.4.0 which started again without any issues.

**Comment by tchapi** [comment]
Hi @pacroix and thanks for the report

The parameter `timezone` is declared [here](https://github.com/tchapi/davis/blob/v4.4.1/config/services.yaml#L9) — do you confirm you also have this line in your version of the source (there should be no reason for you to _not_ have it, but well)?

If you have, then this may just be a problem of application cache. You can try to `rm -rf ./var/cache/` (in the Davis application folder) to force remove all previous versions of the Kernel (that may contain an outdated reference to services, not including the new one)

Please tell me if this worked!

**Comment by pacroix** [comment]
Thanks for the tip, really did the trick. Davis started successfully and shows version 4.4.1

**Comment by tchapi** [comment]
🎉  Great to hear! I'll add a little information note in the README

**Comment by tchapi** [comment]
(Done [here](https://github.com/tchapi/davis/releases/tag/v4.4.1) in the release notes)
