### ISSUE TITLE
IMAP login issue

### ISSUE THREAD

**Issue by rafal72934** [tchapi/davis#139]
I'm not able to login with IMAP credentials. I'm having a similar issue as #66 (initially, I also tried to login to the admin dashboard with regular user credentials). I can successfully login with a test user that I created manually, but when I try with IMAP credentials, I only get: "4.5.0 Sabre\DAV\Exception\NotAuthenticated Username or password was incorrect. Login was needed for privilege: {DAV:}read on ". 

In docker logs:
192.168.208.4 - myuser 11/Feb/2024:07:03:50 +0000 "GET /index.php" 401 

In the container, in /var/log/prod.log, nothing shows up.

I don't see any login attempts in the imap server logs.

I have the environment variables set in the container:
```
/var/www/davis # printenv | grep IMAP
IMAP_AUTH_USER_AUTOCREATE=true
IMAP_AUTH_URL={mydomain.com:993/imap/ssl}
```

I'm not sure how to troubleshoot further. Appreciate any guidance!

**Comment by tchapi** [comment]
Hi 👋🏼 

You confirm you have `AUTH_METHOD=IMAP` in your env too?

**Comment by rafal72934** [comment]
ah, I did, but in lowercase. Now it works. Thank you!
