### ISSUE TITLE
"Mail sent by" hostname

### ISSUE THREAD

**Issue by rafal72934** [tchapi/davis#141]
When I send an invitation to someone, on the invite, it states:

> Mail sent by http://myservername:9000/

Which is the local server name where my docker is installed. Can it instead display the public domain name? (maybe set in the config?) e.g.

> Mail sent by https://www.mydomain.com/

**Comment by tchapi** [comment]
Hi @rafal72934 

It should work out of the box (I myself use Davis in a docker container, and the mails contain the actual final domain name). It depends on how you configured your reverse-proxy to pass the scheme and port to your container.

You can have a look at my setup [here](https://github.com/tchapi/own-private-cloud/blob/master/configurations/davis/nginx.conf) for instance (nginx behind Traefik)

**Comment by rafal72934** [comment]
I have the same Nginx configuration in the Davis docker stack but use a separate gateway server with another Nginx directing the traffic inside the network. Do you know how I should adjust the configuration here?

```
rewrite ^/.well-known/caldav /dav/ redirect;
rewrite ^/.well-known/carddav /dav/ redirect;

location /dav/ {
     proxy_pass http://myservername:9000/dav/;
}
```

**Comment by tchapi** [comment]
Not really a nginx expert here, but I guess you should make sure to forward the correct headers down the stream so that Davis know from which domain you're calling?

**Comment by AkselMeola** [comment]
Maybe this will help if you pass the Host explicitly:
```
    proxy_set_header Host            $host;
    proxy_set_header X-Forwarded-For $remote_addr;
```
https://serverfault.com/questions/598202/make-nginx-to-pass-hostname-of-the-upstream-when-reverseproxying

**Comment by rafal72934** [comment]
Thank you, @AkselMeola. I realized I had those set only in the / location, but not in /dav. Now it works!
