### ISSUE TITLE
Mariadb 11.3(.2?) incompatibility

### ISSUE THREAD

**Issue by holow29** [tchapi/davis#146]
Having issues with MariaDB 11.3.2. Works fine when reverting to 11.2.3.

Getting the following error when trying to check migrations (and I'm guessing on every connection to DB):
`SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Please, report to the developers`

On MariaDB server, it is showing connection is dropped:
`[Warning] Aborted connection 499 to db: 'unconnected' user: 'unauthenticated' host: '172.19.0.2' (This connection closed normally without authentication)`

I am by no means an expert in character sets if this is in fact the issue. In my fastcgi params, I have `charset=utf8mb4` in the DATABASE_URL. Looking at what I can see of the character set differences between the database at 11.3.2 vs. 11.2.3, I see the following change:
11.3.2:
`| character_set_collations | utf8mb4=utf8mb4_uca1400_ai_ci |`
11.2.3:
`| character_set_collations |                              |`

**Comment by holow29** [comment]
https://stackoverflow.com/questions/78036671/mariadb-11-3-2-php-server-sent-charset-0-unknown-to-the-client-please-rep
Seems to be a PHP issue

**Comment by holow29** [comment]
This was just hotfixed in the MariaDB 11.3.2 docker image for compatibility. Fix for PHP still forthcoming, but will now work at least.

**Comment by tchapi** [comment]
Thanks for the heads-up!
