### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by sw030453** [tchapi/davis#148]
A couple of questions:

- How can I put the log in *var/log/dev.log* in a different place (*e.g.,* `/var/log/httpd`)?  Can I send these messages to *syslog*?

- How can I change the logging level for *doctrine* and *security*?  They seem to be set to **DEBUG**...

Thanks in advance.

**Comment by tchapi** [comment]
Hi,

> How can I put the log in var/log/dev.log in a different place (e.g., /var/log/httpd)? Can I send these messages to syslog?

The documentation of Monolog is [here](https://symfony.com/doc/current/logging.html#handlers-writing-logs-to-different-locations), it's quite comprehensive and allows you to write logs elsewhere

> How can I change the logging level for doctrine and security? They seem to be set to DEBUG...

You seem to be running in dev mode. In production mode, we use a "fingers_crossed" type

**Comment by tchapi** [comment]
Closing as no follow-up. Please reopen if you see an issue in Davis 🙏🏼
