### ISSUE TITLE
FR: Calendar sharing

### ISSUE THREAD

**Issue by de-es** [tchapi/davis#15]
Really nice work so far. Much appreciated.

It would be nice to also have the calendar sharing feature available in the UI.

**Comment by tchapi** [comment]
Hi @de-es, could you elaborate a bit on that ? Delegation is already possible via the UI

**Comment by de-es** [comment]
Sure. Only entire accounts can be delegated, so delegates see all calendars of a user. Sometimes you just want to share a single calendar. See https://sabre.io/dav/caldav-proxy/ and https://sabre.io/dav/caldav-sharing/.

SabreDAV already has UI support for calendar sharing when you call e.g. http://<davisurl>/dav/calendars/<user>/default/ under Actions -> Share this resource, but it would be nice to edit that directly in Davis.

**Comment by tchapi** [comment]
Ok, understood. I'm running a bit short of time these days but I will have a look and keep you posted

**Comment by de-es** [comment]
No worries and thank you for taking a look.

**Comment by tchapi** [comment]
Quick question @de-es.

Suppose `userA` gives RW access to its `blue` calendar to `userB` (via the SabreDAV UI).
Is this `blue` calendar not supposed to show in http://____/dav/calendars/userB/ ? I'm not seeing anything while testing rapidly now.

**Comment by de-es** [comment]
It should be available e.g. under http://____/dav/calendars/userB/xxxxxxxx-xxxx-xxxxxxxxx-xxxxxxxxxxxx (x= hexadecimal values) and you should find a new entry in the `calendarinstances` table. The `access` column has 2 for readonly and 3 for R/W.

**Comment by tchapi** [comment]
Ok, got it. There are some subtleties I need to work out then.

**Comment by tchapi** [comment]
Hi again @de-es 

Would you mind testing https://github.com/tchapi/davis/pull/17 to see if it works well from your point of view ?

The user delegation feature was misplaced — at the calendar level, so I refactored that and added individual calendar sharing, which should be what you were looking for.

Thanks a lot

**Comment by de-es** [comment]
Awesome work, everything works as expected afaics.
