### ISSUE TITLE
Can't delete read-only delegate

### ISSUE THREAD

**Issue by de-es** [tchapi/davis#16]
Steps to reproduce:
1. Add a delegate (don't check "Give write access?")
2. Delegate is added correctly.
3. Click Remove button
4. Confirm with "Yes" button
5. Nothing happens, delegate is still listed

When giving write access while adding, I can remove the delegate as expected.

**Comment by tchapi** [comment]
Hi @de-es 

This is indeed a bug and I have identified the cause. I am working on a fix right now

Thanks !

**Comment by tchapi** [comment]
If you have a moment to test it (on `master`), that'd be welcomed !

**Comment by de-es** [comment]
Works like a charm. Thank you!
