### ISSUE TITLE
HTTP 400 Bad Request when trying to share a calendar

### ISSUE THREAD

**Issue by tlansdell8** [tchapi/davis#160]
Hi there,
Firstly Davis is great, love it so far thanks! 
I am a novice at issues but wanted to report this as not sure if I am doing something wrong... When I use the "Sharing" link next to a calendar, choose a user and click "Add", I get a BadRequestHttpException thrown by Symfony. Please see below image, and image of the URL requested.

<img width="1078" alt="Screenshot 2024-06-30 at 15 08 11" src="https://github.com/tchapi/davis/assets/77635900/e4ddc06e-e537-4163-8bf2-f0bf28aad6bb">
<img width="612" alt="Screenshot 2024-06-30 at 15 09 14" src="https://github.com/tchapi/davis/assets/77635900/6f341173-b079-41a8-92ca-d02fe634a54f">

No errors seem to be thrown in either the Nginx access or error logs, so I can just go on what Symfony shows in the screenshot. From what I can tell, the principalId in the URL seems to be numeric, yet the error complains that it isn't. Not sure where to go from here.
To add: Using Davis v4.4.2
Thanks in advance, any help would be greatly appreciated :)

**Comment by tchapi** [comment]
Hi @tlansdell8 and thank you for your report

I'm looking into it!

**Comment by tchapi** [comment]
Hmm - can't reproduce. `24` seems pretty numeric to me :)

Could you add `var_dump($request->get('principalId'));exit;` line 177 to see what is passed to your server?

**Comment by tlansdell8** [comment]
That’s what I thought - if it helps I’m using Nginx and IMAP authentication. 
I’m away this week without my laptop but I’ll do this on Friday or Saturday and report back. Thanks for your help 👍

**Comment by tlansdell8** [comment]
The mystery continues... After adding the line it shows `NULL`. Does that mean somehow the GET variable is not being set correctly?
I am using Firefox but I tried with Safari and got the same `NULL` result. Also just to check I did `var_dump($request->get('write'));exit;` and got `NULL` also. 
Sounds like something in my environment is causing this but I have no idea what!

**Comment by tchapi** [comment]
> Sounds like something in my environment is causing this but I have no idea what!

Weird indeed. Do yo have a specific reverse proxy in front of Davis that could remove GET parameters somehow?

**Comment by tlansdell8** [comment]
I feel a little silly now!! For some reason I didn't have `?$args` at the end of `try_files $uri $uri/ /index.php` in my Ngnix config. Adding this fixed the issue. Thanks for your help and for the pointer! I'll close this now :)
