### ISSUE TITLE
Event invites only send with subject "(via Davis)"

### ISSUE THREAD

**Issue by allnewryan1** [tchapi/davis#165]
In Plugins/DavisIMipPlugin.php, see below comments

original comment: MESSAGE_ORIGIN_INDICATOR is set to "(via Davis)" with no apparent option to add company/individual name owning the calendar (i.e. allnewryan1 (via Davis)).

**Comment by allnewryan1** [comment]
update: it's the $senderName variable not being set correctly

manually set the $senderName and it appears in the subject

**Comment by allnewryan1** [comment]
I added the following from the base class to at least provide the sender's email as a temporary solution.
`...
$senderEmail = substr($itip->sender, 7);
$recipientEmail = substr($itip->recipient, 7);
if ($itip->senderName) {
    $senderName = $itip->senderName.' <'.$senderEmail.'>';
} else {
    $senderName = $senderEmail;
}
if ($itip->recipientName && $itip->recipientName != $recipientEmail) {
    $recipientName = $itip->recipientName.' <'.$recipientEmail.'>';
}`

**Comment by tchapi** [comment]
Hi @allnewryan1 and thanks for the feedback,

`$senderName` is set to the display name of the user sending the invitation. Have you got the display name correctly set?

**Comment by allnewryan1** [comment]
![Screenshot 2024-08-30 143844](https://github.com/user-attachments/assets/3b2e7e13-c298-4b48-8c12-fcff441937d7)
Yes, screenshot is my user settings

**Comment by tchapi** [comment]
Then your `From` header will look like this:

![Screenshot 2024-08-30 at 21 41 39](https://github.com/user-attachments/assets/7cc23c3c-e0f6-483b-9cba-65f5a9592f23)

What client are you using to create the event?

**Comment by allnewryan1** [comment]
![Screenshot 2024-08-30 143844](https://github.com/user-attachments/assets/0176428f-569d-4d3f-954f-a97a9efa2d43)
redacted my email address

**Comment by allnewryan1** [comment]
![Screenshot 2024-08-30 144614](https://github.com/user-attachments/assets/866299b5-230c-41ec-b5b0-1cf33745399c)
Using OneCalendar, headers are as shown

**Comment by tchapi** [comment]
My guess is that your client doesn't send the "senderName" along the iMIP payload. Have you been able to test on another client, by any chance? Or is there any configuration in OneCalendar that would allow you to set this name?

**Comment by tchapi** [comment]
One workaround for your case could be to set `MESSAGE_ORIGIN_INDICATOR` to null, which would totally remove the name in the header, which will probably force the client to display the email

**Comment by allnewryan1** [comment]
See the pull request #166 but closing this as I agree this is likely a client issue now that I've had time to think about it
