### ISSUE TITLE
[Feature Request] For subscribed calendars, deactivate reminder synchronization?

### ISSUE THREAD

**Issue by 1Luc1** [tchapi/davis#173]
Hey,

is there a way to deactivate the synchronization for the notifications/reminder of an calendar?

Example:
```
User A creates Calendar C.
User B subscribes to Calendar C.
User A creates a calendar entry 1 without a notification.
Entry 1 shows within user B calendar
User A adds notification of entry 1 
entry 1 for user B gets changed to have also a notification alert
```

Proposal:
`entry 1 for user B doesn't get change if the notification/reminder was changed on entry 1`

I don't know if this is possible or if this belongs more to a sabre/dav feature request?

Thanks!

EDIT: don't know whats the actual naming for it, so i changed notification to reminder

**Comment by tchapi** [comment]
👋🏼 
Well, the VALARM is part of the VCAL format, so if you share a calendar, you share the full event data, including the reminder (the VALARMs). Otherwise you need to set an alarm only on the client side, but I don't see why a client would propose this feature

**Comment by 1Luc1** [comment]
Thanks for your fast reply and clarification.
I found something, which is kind of related https://github.com/sabre-io/vobject/issues/316. Unfortunately this feature request is from 2016.

**Comment by tchapi** [comment]
> found something, which is kind of related https://github.com/sabre-io/vobject/issues/316.

I see. This seems quite scrappy to remove the VALARMs from the VCAL object but it's one way of achieving the goal. For now, I wouldn't go this route but we could revisit later if there is a strong need

**Comment by 1Luc1** [comment]
I think for now its ok.

I'm just wondering, for other alternative products, how this is done? Like if subscribing to an calendar, does always synchronize also the VALARMS? I mean this way, you can easily interference with others calendar adding some notifications/reminder/valarm to an event and it will pop up a notification/alarm to all who are subscribed to it...
