### ISSUE TITLE
php8 compatibility

### ISSUE THREAD

**Issue by tiiiecherle** [tchapi/davis#18]
Hey,

archlinux just switched to php8 on stable.

Is davis already php8 compatible? If not it would be nice to see it in the changelog of the future compatible release.

Thanks

Kind regards

**Comment by tchapi** [comment]
Hi @tiiiecherle 

I haven't had the time to look at it yet, but I will soon !

**Comment by tiiiecherle** [comment]
o.k., thanks.

**Comment by tchapi** [comment]
v1.6.1 should work in PHP 8 without problems. Open an issue if you find anything that doesn't work

**Comment by tiiiecherle** [comment]
Thanks for the update. After first tests it seems to work well.
