### ISSUE TITLE
Automated Docker Hub build fails because file can't be copied

### ISSUE THREAD

**Issue by n1trux** [tchapi/davis#2]
See the [build.log](https://github.com/tchapi/davis/files/4003487/build.log) for an automated build of 'master:/docker' (cb00eaa9) on Docker Hub.

Source is configured as master, Build context is `/docker`.

Relevant error:

```
Step 7/12 : RUN cd /var/www/ && curl --silent -o ${version}.tar.gz -L https://github.com/tchapi/davis/archive/v${version}.tar.gz && tar xvzf ${version}.tar.gz && mv -f /var/www/davis-${version} /var/www/davis && rm ${version}.tar.gz
---> Running in e80aa7d42f50
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Removing intermediate container e80aa7d42f50
The command '/bin/sh -c cd /var/www/ && curl --silent -o ${version}.tar.gz -L https://github.com/tchapi/davis/archive/v${version}.tar.gz && tar xvzf ${version}.tar.gz && mv -f /var/www/davis-${version} /var/www/davis && rm ${version}.tar.gz' returned a non-zero code: 2
```

Relevant lines in Dockerfile:

```
RUN cd /var/www/ && curl --silent -o ${version}.tar.gz -L https://github.com/tchapi/davis/archive/v${version}.tar.gz \
 && tar xvzf ${version}.tar.gz \
 && mv -f /var/www/davis-${version} /var/www/davis \
 && rm ${version}.tar.gz
```

I guess it's because `${version}` can't be resolved when you're trying to build master; it should be `https://github.com/tchapi/davis/archive/master.tar.gz`. Maybe drop the `v` and set master as the version?

I'm trying if `ARG version="master"` works now.

**Comment by tchapi** [comment]
> I guess it's because ${version} can't be resolved when you're trying to build master

You don't want to build `master`, you want to build a specific release, hence the `version` argument that you must set..

**Comment by n1trux** [comment]
I know, but there's a `v` in front of the version. So when you set the version to `master` it doesn't work.

Ideally you would want to build both `master` and the corresponding versions with the same Dockerfile (or version your master with the next version).

This worked:

```
-RUN cd /var/www/ && curl --silent -o ${version}.tar.gz -L https://github.com/tchapi/davis/archive/v${version}.tar.gz \

+RUN cd /var/www/ && curl --silent -o ${version}.tar.gz -L https://github.com/tchapi/davis/archive/${version}.tar.gz \
```

I'll create a PR.

**Comment by tchapi** [comment]
What I'm saying is you _should not_ build `master`, since it's not guaranteed to be stable. The Dockerfile is here if you want to deploy a stable version of **Davis**. Your fix helps in case you want to develop and test in Docker, but then you'd rather share your actual folder in a volume than create an image.
