### ISSUE TITLE
Composer version not specified, causing docker build failure

### ISSUE THREAD

**Issue by zemsten** [tchapi/davis#23]
The Dockerfile doesn't specify a version in the command to grab and install composer. The newest versions are the 2.x branch, and that doesn't appear to be supported with your current plugins.

A quick fix is to change the Dockerfile compose install to be:
`RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=1.10.21` to grab the lastest releast of the 1.x branch.
I imagine best practice would be to migrate plugins to support version 2 though.

**Comment by tchapi** [comment]
Hi @zemsten and thanks for your issue

You are right, I should be more specific on the Composer version. I'll have a look at that soon.
I'll revamp the way the Docker image is built too, it needs some refreshment I guess

Thanks

**Comment by tchapi** [comment]
Hi @zemsten 

Would you mind having a look at #24 and see if it fits your needs and seems sensible ?
I migrated to Composer 2 (long overdue!) and changed the way the Dockerfile is building the app.

I will probably coin v2.0.0 because this is a breaking change

Thanks !

**Comment by zemsten** [comment]
> Hi @zemsten
> 
> Would you mind having a look at #24 and see if it fits your needs and seems sensible ?
> I migrated to Composer 2 (long overdue!) and changed the way the Dockerfile is building the app.
> 
> I will probably coin v2.0.0 because this is a breaking change
> 
> Thanks !

Certainly! I don't have any real experience with composer, but I'll take a dive into it. The docker side is pretty simple, so I doubt you need any review there. But I'll tinker and get back to you. I generally don't have too much time except weekends. My initial pull and build though doesn't error out, so that's a good sign! Thanks for working on it!

**Comment by zemsten** [comment]
Definitely going to have to brush up on my PHP...

Everything builds, but unfortunately I'm getting a 500 after authenticating on the dashboard page. Haven't had the time to look into that yet, but I imagine it's a reverse proxy issue with NGINX talking to the davis app. I don't see any changes in that config, so I imagine it's somewhere in composer.

When you ran it did you get full functionality?

Additionally, I do think it's probably a good idea to add a named volume to the MySQL docker image if you want persistence there. After I figure out what's going on to cause the 500, I can add that in the changes. That one is easy, at least.

**Comment by tchapi** [comment]
👋 ☕ 
Yes, you're right for the named volume. The docker-compose is really just an example though, for other developers to build upon, but I'll gladly accept a PR for that ;)

**Comment by zemsten** [comment]
Well I've had some time to tinker. Everything looks great, and so far the only change I made is to add a named volume for the SQL container. 

On  my last run though, I did just notice that I can't get the sharing menu to pop up for any calendar in the webUI. Several browsers and the same thing.

**Comment by tchapi** [comment]
You mean by clicking on the button here ?

![Screenshot 2021-05-05 at 17 09 43](https://user-images.githubusercontent.com/1944007/117164251-bbbf3e00-adc4-11eb-8b5f-cb658e3b7b8a.png)

Would you share any error that displays in the console of your browser ?

**Comment by tchapi** [comment]
This issue is closed by the related PR, but if you have another issue with the sharing menu, do not hesitate to create a new issue @zemsten
