### ISSUE TITLE
Feature: Set custom base URL

### ISSUE THREAD

**Issue by tandy-1000** [tchapi/davis#29]
It would be nice to be able to set a base path, so that Davis can be accessed from a subdomain like so: `http://localhost/davis/`

**Comment by tchapi** [comment]
Hi @tandy-1000 

This seems like something that your reverse-proxy should be able to do — Davis is a Symfony app, so something like that: https://www.digitalocean.com/community/questions/make-symfony-works-in-a-subfolder-with-nginx would be of interest for instance, if you use Nginx (this should be straightforward with Apache too)
