### ISSUE TITLE
Composer hints, dav update and openssl issue

### ISSUE THREAD

**Issue by tiiiecherle** [tchapi/davis#3]
Hey,

there are three things I'd like to mention:

1. During composer install there is the following output:
```
Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.
Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
```

2. Dav was updated to version 4.1.0. Would be nice to see this integrated.

3. After updating to openssl 1.1.1.e [this issue](https://github.com/openssl/openssl/issues/11381) came up. I don't know if there is anything there can be done about it in davis/dav to make both peers always send the close notify correctly or if it needs a(n additional) fix from apple for the clients. I downgraded to openssl 1.1.1.d for now.

Thanks in advance. I hope you are doing well.

**Comment by tchapi** [comment]
Hi

1. This is a sub-dependency, nothing to worry about, you can ignore the warning.
2. I'll look into this yes
3. Doing something in davis to fix this problem, if possible (I don't think so) would be counterproductive anyway. It should be done on the client side.

BR

**Comment by tchapi** [comment]
https://github.com/tchapi/davis/releases/tag/v1.4.7

**Comment by tiiiecherle** [comment]
@tchapi 
Thanks, the update worked smoothly with my script.

Another issue occurred when testing notes functionality. I added a calendar (with notes functionality to a user) but neither the macOS nore the iOS client can see the notes. I can only activate calendars or reminders in both of them. Shall we continue here or shall I open another issue?

Thanks for the help in advance

Kind regards
