### ISSUE TITLE
Using CalDav with iOS

### ISSUE THREAD

**Issue by trashcoder** [tchapi/davis#31]
i tried to use DAVis with iOS and can't connect to the server:

In Thunderbird with Lightning everything works fine, but with iOS i got these error messages:

[30/Jul/2021:10:43:02 +0000] "PROPFIND /dav/principals/dennis/ HTTP/1.1" 401 3552 "-" "iOS/14.7.1 (18G82) accountsd/1.0"
[30/Jul/2021:10:43:03 +0000] "PROPFIND /dav/principals/dennis/ HTTP/1.1" 207 3676 "-" "iOS/14.7.1 (18G82) accountsd/1.0" [30/Jul/2021:10:43:03 +0000] "OPTIONS /dav/principals/dennis/ HTTP/1.1" 200 967 "-" "iOS/14.7.1 (18G82) accountsd/1.0"

**Comment by tchapi** [comment]
Hi @trashcoder

I'm personnally using davis (and the underlying sabre/dav implementation) on an iPhone and it works well.

Those logs are just the access logs but do not tell much. Are you sure that you credentials are good ? It's well known that the iOS DAV implementation is more picky than any third party app implementation, so you might want to investigate on this side.

BR

**Comment by trashcoder** [comment]
Well, i'm a bit lost now. Where can i find out, what's wrong with my configuration?
In my other container i got Baikal work with my iphone after i made the .well-known configuration in my .htaccess.

in davis i i made the configuration described in the README.md except the SetEnv Parameter in the Apache File. I entered the parameter in .env.
Do you run davis with apache or nginx? perhaps nginx is easier to set up?

**Comment by tchapi** [comment]
I run it with Traefik through docker containers. You can find my setup (roughly) here if that helps: https://github.com/tchapi/own-private-cloud/blob/master/docker-compose.yaml#L174-L223

**Comment by tchapi** [comment]
And a very standard nginx configuration to reverse-proxy PHP-FPM: https://github.com/tchapi/own-private-cloud/blob/master/configurations/davis/nginx.conf

**Comment by trashcoder** [comment]
thank you.

**Comment by Nonolanlan1007** [comment]
I actually have the same issue. For an unknown reason, my calendar doesn't display on iOS, whereas on Thunderbird with the same configuration I have no problems. Did I make a mistake during configuration on iOS? What exactly did you mean when you said "the iOS DAV implementation is more picky than any third party app implementation"?

https://github.com/user-attachments/assets/9fe5043f-8239-44d9-8b44-2165efcac3a3

![Image](https://github.com/user-attachments/assets/75cc191f-3e4c-4459-b05d-b0e2cf781c95)
