### ISSUE TITLE
Field 'calendarorder' doesn't have a default value

### ISSUE THREAD

**Issue by JodliDev** [tchapi/davis#35]
I am not exactly sure if this is a bug in davis, or the web calendar I am using. Maybe you have more knowledge on what exactly is going on:
Since 1.8.0, creating a new calendar fails with the error message:
> SQLSTATE[HY000]: General error: 1364 Field 'calendarorder' doesn't have a default value

For now, I fixed it by adding the default value '0' to the 'calendarorder' column in the table 'calendarinstances'. But could this cause other problems?

I am using MariaDB 10.3.31on Ubuntu

Thank you :)

**Comment by tchapi** [comment]
Hi,

It doesn't seem linked to 1.8.0 as far as I can tell, but to a discrepancy between the migrations and a legacy Baikal installation (_that already has a default value for this column_).

I've added a migration on `master`, it should be enough.

Thanks a lot !

**Comment by tchapi** [comment]
See https://github.com/tchapi/davis/commit/4f6fc9ed01feb39c1e2e89a01e857b0d3fe3fb0f
