### ISSUE TITLE
Update to 1.9.0 breaks installation

### ISSUE THREAD

**Issue by tiiiecherle** [tchapi/davis#49]
Hey, 

after updating to 1.9.0 the complete server does not work and returns the following server error. I attached a screenshot.
![Bildschirmfoto 2022-01-14 um 09 35 46](https://user-images.githubusercontent.com/7059936/149489416-f3bb5883-1f22-43fe-bca2-0eef862be2ee.jpg)

I did not change anything and downgrading to 1.8.0 solves the problem.

Thanks for looking into it in advance.

**Comment by tiiiecherle** [comment]
Additional info: I still use an installation without docker.

**Comment by tchapi** [comment]
Hi @tiiiecherle 

Could you provide me with the PHP logs / the Symfony logs ? I will have a look

PS: did you update the `.env` file correctly with `MAILER_DSN` ?

**Comment by tiiiecherle** [comment]
Hey,

sorry for the issue, after getting confused with [this](https://github.com/tchapi/davis/issues/48) I changed it to DNS instead of DSN. Now everything seems to work with version 1.9.0.

Thanks a lot
