### ISSUE TITLE
v.1.9.0 Docker image does not work: after spinnup only "file not found"

### ISSUE THREAD

**Issue by tfendler** [tchapi/davis#50]
Hi,
I am just trying to setup the server with the current docker image you published.
Unfortunately, there seems to be something wrong with the permissions inside the container.
When you start the container and try to access it, you only get a "file not found". I tried to correct the permission inside the container, but unfortunately I failed. After some corrections I now get a 500-Error. 
EDIT: I tried to start with the "Full-Stack". but as described it starts an builds the container right, but when you try to access the frontend, it just give the error.

Could you please check, what might be wrong with the permission setup?

Cheers Thorsten

**Comment by tchapi** [comment]
Hi Thorsten

Thanks for the report. Would you be kind enough to test with the latest `1.8.*` container ?

**Comment by tfendler** [comment]
Hi tchapi,
i get the same results with the 1.8.0 container.... I am running docker-compose 2.2.2 do you think, this might be a problem.
Do you know, what release was the last "known" running version with the full-stack docker-compose? Maybe I try that, just to make sure, its no misconfiguration on my end?
Cheers.

**Comment by tchapi** [comment]
Hi @tfendler,

Thanks for your research.

The `var` folder references the `/var/www/davis/var` folder that is used by Symfony to write some cache and logs, so you should keep this `RUN chown -R www-data:www-data var` line anyway (even if you want to add the one you mention).

I think there is a configuration problem somewhere and you're right that the user rights may be the culprit. However I run the Docker image (_from this package_) in production myself without any problems.

Have a look at my other docker-compose file that I use here: https://github.com/tchapi/own-private-cloud/blob/master/docker-compose.yaml#L176-L222 and the corresponding Dockerfile for nginx: https://github.com/tchapi/own-private-cloud/blob/master/build/Dockerfile-davis-proxy

To be sure, I just cloned this repository fresh, changed to the `docker` directory, did a `docker-compose up -d` and then created the base schema with `docker-compose run davis bash -c 'bin/console d:s:u --force'` and I can access the frontend without any permissions issues.
