### ISSUE TITLE
Feature Request: LDAP Integration

### ISSUE THREAD

**Issue by IronTooch** [tchapi/davis#55]
Seems like a pretty normal use case, to extend the authentication schema to support LDAP. 

I know I can submit a pull req, but if an actual PHP developer where more comfortable integrating this feature, it would likely be better / faster than me trying to figure out how to do it.

**Comment by tchapi** [comment]
Hi @IronTooch 
This should rather be done at the sabre/dav level.
An attempt was made some time ago, but I don't think anybody tried to finish this work: https://github.com/sabre-io/dav/issues/838

**Comment by tchapi** [comment]
See also https://github.com/sabre-io/Baikal/issues/321 on Baikal (which is also using sabre/dav)

**Comment by IronTooch** [comment]
Oh, for sure, integrating at the Sabre level is certainly better. But since they don't seem inclined to integrate it, it might be able to be scaffolded at this layer instead with an integration that makes regular users from an LDAP source. That being said, if you want to close this for the same reason the Baikal team closed theirs, I understand.

**Comment by tchapi** [comment]
I'm fine with leaving it open if someone feels like trying — I'll gladly review a PR.

Unfortunately I myself have little time and no interest in LDAP as I don't use it on a day-to-day basis.

**Comment by reven** [comment]
Oh, just realized this may be helpful here too: 
https://github.com/Excision-Mail/ansible-baikal/blob/main/files/baikal-0.9.1-ldap-auth-and-smtp.patch

**Comment by tchapi** [comment]
Hi @IronTooch 
I could give it a go, since the patch provided by @reven is quite close to what an actual implementation might look like and I have some free time to work on Davis.

Would you be able to test it with a real LDAP server (I don't have any at hand) if I create a branch for that ?

**Comment by IronTooch** [comment]
Sure can!

**Comment by tchapi** [comment]
Great, will keep you updated really soon !

**Comment by tchapi** [comment]
See https://github.com/tchapi/davis/pull/61 — if you can test it and tell me if everything is nominal, that would be awesome @IronTooch !

**Comment by IronTooch** [comment]
Okay, so does not work at the moment, but I'm kind of at a loss on how to troubleshoot. @tchapi , can you tell me where the relevant logs would be?

I can say the most likely reason why is because the given variables don't seem to have any way of setting the Bind user for LDAP, so there's no way to authenticate to search / enumerate the directory. I tried digging into the pull req, but I couldn't figure out where that would go. src/Services/LDAPAuth.php has an LDAP Open call that seems to ask for a user name, but I'm not sure where it's set. My understanding of Bind is that you have to auth to the server first, before seeing if the user in question is any good. I did try to just connect to the admin interface as a valid user in my directory, and that was unsuccessful (`Username not found`).

Here is the relevant data from an authenticated LDAP directory search:
```
test_user, virtual-groups, ldap.tucc.io
dn: cn=test_user,ou=virtual-groups,dc=ldap,dc=tucc,dc=io
goauthentik.io/ldap/superuser: false
cn: test_user
uid: 72c328974474361eb03f4a83568203fb1dbd722561e7e8968befbc4f8077fa69
sAMAccountName: test_user
gidNumber: 2009
objectClass: group
objectClass: groupOfUniqueNames
objectClass: goauthentik.io/ldap/group
objectClass: goauthentik.io/ldap/virtual-group
member: cn=test_user,ou=users,dc=ldap,dc=tucc,dc=io
```

**Comment by IronTooch** [comment]
Also relevant Screenshot from Admin Interface
![image](https://user-images.githubusercontent.com/27360514/157761776-83dff858-5f56-4841-acf6-3348abc9872f.png)

**Comment by tchapi** [comment]
Hi @IronTooch 

Thanks for your test. I think you are trying to connect to the admin interface with your LDAP user, which is not possible (There is only one "admin dashboard" user, it's `admin` by default and it's configured in the env vars.

What you want to try is to connect to http://yourserver.org/dav with your credentials and see how it works. If it's successful, you will be able to browse your DAV objects in the browser. If not, you will see an XML error page

Tell me how it goes
Thanks

**Comment by IronTooch** [comment]
Ah, I see! Okay, so still no luck, but different error:

```
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:sabredav-version>4.3.1</s:sabredav-version>
<s:exception>Error</s:exception>
<s:message>Call to undefined function App\Services\ldap_connect()</s:message>
</d:error>
```

**Comment by tchapi** [comment]
Ok, this error seems to indicate that your PHP version was not compiled with LDAP. So you need to either reinstall it correctly, or add the module. I cannot really help you here since it really depends on your platform ... but you should be able to find a tutorial for that. Ex. if you're on Debian: `apt-get install php-ldap`

**Comment by IronTooch** [comment]
Okay, so now I'm getting the HTTP login screen, but the authentication is not operational:
![image](https://user-images.githubusercontent.com/27360514/157992051-8ac05d64-48b2-41b5-ae4c-9da38b8b00c7.png)

I.e., when I type a user I know to be correct, it just re-presents me the login screen repeatedly, as opposed to allowing the user through.

Nothing of note in the following log locations:
`/var/log/syslog`
`/var/log/nginx/mysite.error.log`
`/var/log/php7.4-fpm.log`

Output of `php -m`

```
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gettext
hash
iconv
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Comment by tchapi** [comment]
Ok thanks. Several thoughts:
  - you may find more logs in `var/log/*` in the Symfony installation, maybe something worth it in there
  - any log on the LDAP side, by any chance (like "password is not good" or "user does not exist" for instance) ?
  - have you tried with a `user@domain.com` type of login instead of just `user` ?

**Comment by tchapi** [comment]
Re: I tried to run a standard openldap container locally (with https://hub.docker.com/r/bitnami/openldap/) with the default configuration, and I can login with `admin` /  `adminpassword`.

The configuration I used on Davis is: 

```
LDAP_AUTH_URL="ldap://localhost:1389"
LDAP_DN_PATTERN="cn=%u,dc=example,dc=org"
LDAP_MAIL_ATTRIBUTE="mail"
LDAP_AUTH_USER_AUTOCREATE=true
```

It's the first time I work with LDAP so I don't really know if it's good but apart from a problem with `ldap_read()` (_stating that it cannot find such object, which is likely a configuration problem on the LDAP side_), I could login without problem.

I've added a try/catch and my setup with the default openldap container works (I can login with admin, and it autocreates the user)

**Comment by IronTooch** [comment]
Okay, a working pattern definitely helped. I didn't include the port on the LDAP connection (assumed it would default to 389), and my DN pattern was off. I'm now able to log in, though some things render oddly at the moment (see screenshot). 
![image](https://user-images.githubusercontent.com/27360514/158083961-ab93f5d7-4bac-4924-82b3-74f14b858ffb.png)  

This was my (working) config:
```
LDAP_AUTH_URL="ldap://10.1.40.5:389"
LDAP_DN_PATTERN="cn=%u,ou=users,dc=ldap,dc=tucc,dc=io"
LDAP_MAIL_ATTRIBUTE="mail"
LDAP_AUTH_USER_AUTOCREATE=true
```

That being said, I *am* able to see the new user in the Admin interface, so it looks good from my side. 
![image](https://user-images.githubusercontent.com/27360514/158083977-9ec1645b-008c-43e8-a596-c0523463a0d1.png)

I'm going to spin up a client instance to test, but on first shake, it looks like this works.

**Comment by tchapi** [comment]
Great ! This is fantastic.

On the screenshot, the only thing I see that is not rendered correctly is the Symfony debug bar at the bottom of the page — which is normal (the page is rendered via a subtly different way than normal pages) and not really a concern (it's only displayed when the app is in _dev_ mode): this will not happen in production mode.

**Comment by tromlet** [comment]
So, would the end goal of all of this be to ultimately get "LDAP" as an option for the drop-down in the "WebDAV Authentication Type" drop-down menu under "System Settings"?

**Comment by tchapi** [comment]
Hmmm ... what dropdown are you talking about ? 🤔
