### ISSUE TITLE
Production environment hardening: underlying Sabre/DAV accessible through HTTP.

### ISSUE THREAD

**Issue by reven** [tchapi/davis#57]
This might be an error on my part because of permissions or setup: while testing login through IMAP, I accessed http://www.example.com/dav/ with my browser and got a login prompt. I provided a user (non admin) credentials and after success (yay!) I was redirected to the underlying Sabre/DAV framework. I can fully navigate all the nodes and structures.

Is this intentional? Is this a misconfiguration issue on my end? I'm using Nginx and I pasted the example config (just added SSL and my env vars).

![image](https://user-images.githubusercontent.com/206993/155511051-79bbf966-3b24-4ddf-866f-270d103c9953.png)

**Comment by tchapi** [comment]
What you're browsing here are the collections of the user in question, so it seems normal. You can navigate all the nodes of your user: calendars, addressbooks and whatnot, but only for your user (or the delegations that your user have)

Have I understood correctly ?

**Comment by reven** [comment]
Oh, ok. I thought I had broke something. It just seemed strange to be able to access the underlying library like that.

Btw @tchapi, thanks for all the work you're putting into this. This is great.
