### ISSUE TITLE
Can not sync events with invitations

### ISSUE THREAD

**Issue by marc2016** [tchapi/davis#59]
Hey,

after my update to version 1.9.1 I can not sync events with invitations. On MacOS I get the error 500: for CalDAVWriteEntityQueueableOperation. I can not found any log messages for this error. Where can I find additional information?

Thanks in advance :-)

**Comment by marc2016** [comment]
I found a 401 error in the access log, because the system could not send emails. I changed the MAILS_DSN environment variable of the docker container to MAILER_DSN=smtp://${MAIL_USERNAME}:${MAIL_PASSWORD}@${MAIL_HOST}:${MAIL_PORT}.
With this setting events with mail addresses working. 
I wil create a pull request for the docker compose file.

**Comment by tchapi** [comment]
Hi
As far as I can tell, the Docker compose file is correct, no ?

**Comment by marc2016** [comment]
Hi,

sorry I missed that fix in the last pull request. I have created a new one: https://github.com/tchapi/davis/pull/62
Thank you :-)
