### ISSUE TITLE
after install Docker new Users cannot login

### ISSUE THREAD

**Issue by swoop124** [tchapi/davis#60]
Hello,

i just installed Davis with Docker-Compose as described. it worked fine, only Web-Dav is disabled.
But after i created several Users, no user but Admin can login.
I get this message: Username could not be found.
But i checked in the Database: Davis in Table users is an entry for each User i created, with a hashed password, i guess. 

Did i do something wrong?

regards

**Comment by tchapi** [comment]
Hi @swoop124 
Do you try to login to the administration interface ? Only the admin can do that. The user you create are DAV users, they don't have access to the administration interface.

**Comment by swoop124** [comment]
hello,

thanks for the reply.
yes, i thought, that davis has a frontend, but it is a Server-app.
So i have to search for another tool, but i will try it for another project.

regards
