### ISSUE TITLE
No sign of invitations being sent

### ISSUE THREAD

**Issue by skug67** [tchapi/davis#65]
I'm running davis directly via Apache2 (no docker) and I can get events to sync w/no problem.  However, even though I have configured the environment with both MAILER_DSN (using postfix on the same machine -- having tried both localhost and a FQDN for the smtp URL) and INVITE_FROM_ADDRESS, I see no signs in either [path-to-davis]/var/log/dev.log or in my system mail logs that there is any attempt to actually send an invitation.

I'm perfectly prepared to believe that I set something up wrong, but without even a clue in the logs, I'm at a loss for debugging this myself.

**Comment by tchapi** [comment]
Hi,
Can you share your configuration regarding the mail setup (without personal info or credentials of course) ?

**Comment by skug67** [comment]
I've tried (at least) the following variations:

MAILER_DSN=smtp://[FQDN]:465?encryption=ssl&auth_mode=login&username=[USERNAME]&password=[PASSWORD]

and 

MAILER_DSN=smtp://[FQDN]:587?encryption=tls&auth_mode=login&username=[USERNAME]&password=[PASSWORD]

MAILER_DSN=smtp://localhost

there may have been other variations that I didn't save for posterity

**Comment by skug67** [comment]
Tried that formulation as well.  No joy.  Still complete silence in the postfix logs, and nothing including "smtp" or "SMTP" or my FQDN in dev.log either

**Comment by skug67** [comment]
OK, looks like the problem was client side.  I was testing with DAVx5 on Android, but was giving the account a name other than my email because I didn't want to conflict with the existing caldav account I was using (baikal -- with the intent to migrate to davis).  When I renamed the account to use the email address everything started to work fine.

Thanks to all for quick responses/suggestions.

**Comment by tchapi** [comment]
Glad you made it work ! 🎉
