### ISSUE TITLE
How to get detailled logs?

### ISSUE THREAD

**Issue by michaelkrebs94** [tchapi/davis#66]
I am currently setting up Davis inside docker-compose and struggling to get the IMAP Auth working.

Unfortunately there seems to be no logging available which could be of any help for "Username could not be found."
I would expect to see some more details in the logs, e.g. if the IMAP server connection could be established, what the response of it was etc. 

The only logging in docker-compose is this style:
11/May/2022:22:37:01 +0000 "POST /index.php" 302

**Comment by tchapi** [comment]
Hi
You can get logs directly in the container, but I think you're trying to log in the backend with a normal user, right ? Like in https://github.com/tchapi/davis/issues/60 ?

**Comment by michaelkrebs94** [comment]
Thanks, I think that answers my question 😊
