### ISSUE TITLE
Http basic auth support?

### ISSUE THREAD

**Issue by poVoq** [tchapi/davis#67]
A lot of self-hosted webservices support so called http basic auth, that simply returns a 200 code if the username and password are correct.

Would be nice if this could be added as another auth option to Davis.

Specifically I would like to auth against this:
https://modules.prosody.im/mod_http_auth_check.html

But I believe many other web-apps would be compatible.

Thanks!

**Comment by tchapi** [comment]
See https://github.com/tchapi/davis#configuration for all the authentication configuration (including Basic Auth)

**Comment by poVoq** [comment]
? This does not explain at all how to authenticated against an external website using the http basic auth standard?

**Comment by tchapi** [comment]
Hmm, this is not supported. Only IMAP and LDAP have been created so far. If you want to create a PR for it, I'll gladly review it (see https://github.com/tchapi/davis/commit/02888d1150e6bdd6ff2d7fb3c09ff911da47fd6f for example as a starting point)
