### ISSUE TITLE
/dashboard not found

### ISSUE THREAD

**Issue by rflrkn** [tchapi/davis#7]
I just tried installing davis onto my server (just like described in the readme.md), but when trying to access the admin interface I'm getting an 404 error. What am I doing wrong here?

**Comment by tchapi** [comment]
Hi,
If the error comes from your webserver, it may be a configuration issue on your side. If it's from Symfony, can you tell me what the debug bar / logs give you ?

**Comment by JoshuaCrewe** [comment]
UPDATE:

`composer require symfony/apache-pack` => This solved it for me as per https://symfony.com/doc/current/setup/web_server_configuration.html#adding-rewrite-rules

I am leaving the rambling below so my path to a solution can be seen.

---

I think I am being a little bit slow here but I can't see how routing is supposed to be working in this app. I followed the instructions in the Readme to get a working set up. I can see the front page fine with all the styles and a link to the admin interface.

When navigating to /dashboard I get a apache 404. The server logs are not saying anything other than that. Looking at the nginx / apache config examples there doesn't seem to be anything in there which is particularly standout special. I can't see the specific configs for the server I am using right now so I will need to set the app up again somewhere else where I have control over the server configs. The hosting is good PHP hosting designed for WordPress, Laravel and generic PHP apps though. I would have thought if it could do Laravel it could do a Symphony app.

**Comment by tchapi** [comment]
Hi @JoshuaCrewe 

You shouldn't need to install a supplementary package. Can you provide your apache vhost config so I can have a look ? The routing is handled by Symfony itself.

**Comment by JoshuaCrewe** [comment]
@tchapi I haven't done much digging around as when I got it working I proceeded to assess the functionality of the app. (It looks great by the way!)

I can try and get the vhost from the hosting provider. It is a managed system so it isn't something I have set up. I will do it locally and see if I get the same issue, I did set that one up!

**Comment by tchapi** [comment]
No problem, don't worry. If it's a shared hosting, I think I understand why it doesn't work right out of the box.

I will add a pragraph in the readme for the package you installed, it looks like it is a good solution in this case

Thanks !

**Comment by tchapi** [comment]
(https://github.com/tchapi/davis/issues/46)

**Comment by JoshuaCrewe** [comment]
Groovy. I am happy to go spelunking for any information that might be useful / interesting to you. I suppose that technically it is a shared hosting platform. It is a management UI on top of digital ocean.

**Comment by JoshuaCrewe** [comment]
Absolutely I can test. I need to finish testing the functionality with a team member and then I can do a git pull and see how it handles it :)

**Comment by JoshuaCrewe** [comment]
Pulled down the lastest git and looks like it is working fine. What I will do is set up on a new space to check the out of the box experience.

I did add the symphony package for using sendgrid to manage email SMTP and obviously added the apache-pack as well.

@tchapi did I read somewhere that you use Apple products with this thing ?

**Comment by tchapi** [comment]
Yes, I do use Apple products (Mail, contacts, on iOS and macOS) and it's working perfectly fine. To be honest, it's `sabre/dav` that does the main work behind the scenes for the Caldav and Carddav protocol.

**Comment by JoshuaCrewe** [comment]
Good to know. I am getting my head around organisation and the different clients (I am Linux, everyone else is mac) and it is all working. The only thing I can't figure out is accepting invitations. I can accept them and people outside the organisation can accept them. This is not reflected in Apple Calendar though. It is a head scratcher but that might be cause it is 5pm here!

**Comment by tchapi** [comment]
Yes, there is an outstanding issue with attendance, but it's complex and to date, I haven't found a workaround. See this discussion for more details: https://github.com/sabre-io/vobject/issues/453 (in fact, most of us are clueless)

I haven't had much time to dig into it too, and much time to fully understand the spec to be honest (_the spec is rather blurry in this regard, in my opinion_)

Any inputs welcome !

**Comment by JoshuaCrewe** [comment]
@tchapi thanks for the link. I will check that out. I was sat there scratching me head thinking "I don't understand how any of this works." or not work as the case may be! Not to worry, for us it isn't a deal breaker. It is not like it worked properly when using Apples own caldav implementation either.
