### ISSUE TITLE
Installation on shared hosting often not possible

### ISSUE THREAD

**Issue by T3rm1** [tchapi/davis#70]
The structure of the project creates problems on some shared hoster platforms. Let me give an example:

So for shared hosting the document root could be `/var/www/vhosts/hostingXXXXX.netcup.net/cal.domain.com/davis/public`. The repository is in the folder `davis` and only the `public` folder is exposed.
The hoster sets the `open_basedir` setting to the same path. This is not changeable. This results in errors as other php files cannot be accessed, for example those in the `vendor` folder.

Is there anything that can be done about this?

Adjusting the `vendor-dir` does not work because of https://github.com/tchapi/davis/blob/e67fad32cdf475cbcca67caddf9feddf1df9d7e0/bin/console#L16

**Comment by tchapi** [comment]
Hi @T3rm1 

It's not really Davis per se, but Symfony. Deploying a somewhat complex application with dependencies, rw rights, etc, on a shared hosting is always a pain.

I found [this article](https://medium.com/@runawaycoin/deploying-symfony-4-application-to-shared-hosting-with-just-ftp-access-e65d2c5e0e3d) that may help maybe ?

**Comment by T3rm1** [comment]
Thanks for the link.
I just received a response from the hoster and they offered to set the open_basedir path to the webhosting root instead of document root. With that change it works.
