### ISSUE TITLE
Disk quota for WebDAV?

### ISSUE THREAD

**Issue by poVoq** [tchapi/davis#75]
Is it possible to limit the storage use per user on WebDAV to something like 1GB?

That would make it easier to manage the storage space use when multiple users are using Davis.

Thanks!

**Comment by tchapi** [comment]
Hi @poVoq 

Good question. This looks like it would be possible reading [this](https://sabre.io/dav/per-user-directories/) to have a directory per user, and then enforcing limits per directory in the filesystem, but it's a bit complicated.
