### ISSUE TITLE
DAVx5: Received non-XML 207 Multi-Status

### ISSUE THREAD

**Issue by das-bub** [tchapi/davis#8]
Hi,

I'm getting the error above when trying to use davis with DAVx5.
The content-type returned is text/html and DAVx5 only accepts xml.
Is there a way to fix or force the content-type returned?
I'm using nginx 1.16 with php-fpm 7.3.

Other clients, like iOS and the Thunderbird Lightning extension work fine as is btw.

Thanks.

Debug log: [davx5-info.txt](https://github.com/tchapi/davis/files/4652139/davx5-info.txt)

**Comment by tchapi** [comment]
Hi @das-bub

Davis does not modify the actual response from sabre.io/dav in this case, so I guess the actual issue, if there is one, is more on their side (see https://github.com/sabre-io/dav/issues/).

It could also be a difference of implementation in DAVx5 regarding your specific use case.

What is the url / parameters that trigger this error exactly ?

**Comment by das-bub** [comment]
Thanks for the quick response.

Right, I wasn't really sure where to file it, so I did it here first.

Based on [this](https://www.davx5.com/tested-with/baikal) I used this URL:
https://example.org/dav/

I also tried the following:
https://example.org
https://example.org/dav/principals/test
https://example.org/dav/calendars/test/default
https://example.org/dav/addressbooks/test/default

They all seem to trigger the same error, because of the well-known redirect.

As for the parameters it's just the username and password, which works just fine with the clients mentioned above.

**Comment by das-bub** [comment]
@tchapi please take a look at the response I got on the upstream issue.

**Comment by tchapi** [comment]
Can you craft a cURL with the full request, including headers, data, etc so I can reproduce your issue ?

**Comment by das-bub** [comment]
I had to put it into a txt file, cause github truncates the command for some reason, but is this what you are looking for?

[curl.txt](https://github.com/tchapi/davis/files/4658508/curl.txt)

It's the request DAVx5 sends, taken from the davx5-info.txt above.

The response I get has content-type: text/html; charset=UTF-8.

**Comment by tchapi** [comment]
Thanks a lot. Let me have a look.

**Comment by tchapi** [comment]
Hello @das-bub 

I think https://github.com/tchapi/davis/releases/tag/v1.4.8 will fix this issue. Can you confirm ?

**Comment by das-bub** [comment]
Yes, v.1.4.8 fixed the issue for me, DAVx5 works fine now.

Thank you very much.

**Comment by tchapi** [comment]
You're welcome !
