### ISSUE TITLE
Address book sharing

### ISSUE THREAD

**Issue by lightmaster** [tchapi/davis#87]
The readme mentions calendar creation and sharing, and address book creation and sharing. I found how to share calendars (both specific ones and all of a users), but I don't see a way to share address books between users.

**Comment by de-es** [comment]
Address book sharing is not supported by the underlying SabreDAV. See https://github.com/tchapi/davis/issues/52

**Comment by tchapi** [comment]
Hi @lightmaster 
You're right that the readme mentions it, and it's actually not true since SabreDAV doesn't allow it. Care to make a PR to change the readme? Oherwise I'll do it later this week

**Comment by lightmaster** [comment]
Created a PR for it

**Comment by lightmaster** [comment]
> Address book sharing is not supported by the underlying SabreDAV. See #52

I saw that when I searched for "sharing", but based on the title and beginning of it assumed it was something else entirely. Shame Sabre/DAV doesn't have this feature considering Baikal talked about implementing it back in 2016 but never did

**Comment by de-es** [comment]
It is, indeed. AFAIK Nextcloud has an implementation for shared address books and they use SabreDAV as well. But it seems like overkill using NC just for CalDav and CardDAV.

**Comment by tchapi** [comment]
I'll keep and eye out if ever I find some way to bake it in without rewriting SabreDAV but it seems compromised. Closing for now
