### ISSUE TITLE
[Docker] doctrine:migrations:migrate - syntax error, unexpected variable "$this"

### ISSUE THREAD

**Issue by JanJastrow** [tchapi/davis#89]
Hi, I tried to run this project locally but keep running into this error:

```
~/Git/GitHub/davis/docker/ docker exec -it davis sh -c "APP_ENV=prod bin/console doctrine:migrations:migrate --no-interaction"

21:10:38 CRITICAL  [console] Error thrown while running command "doctrine:migrations:migrate --no-interaction". Message: "syntax error, unexpected variable "$this" ["exception" => ParseError { …},"command" => "doctrine:migrations:migrate --no-interaction","message" => "syntax error, unexpected variable "$this""]

In Version20230209142217.php line 38:

  syntax error, unexpected variable "$this"


doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] [<version>]
```

---

Steps to reproduce:

- git clone
- cd docker
- docker compose up -d
- %wait%
- [+] Running 4/4
- Run `docker exec -it davis sh -c "APP_ENV=prod bin/console doctrine:migrations:migrate --no-interaction"`

I also tried it with the PosgreSQL version (`docker compose -f docker-compose-postgresql.yml up -d`), same error.
The webinterface just returns error 500.

---
Testing on macOS 12.6.3
Docker version 20.10.22, build 3a2c30b

**Comment by tchapi** [comment]
Hi @JanJastrow and thanks for the detailed issue.

You are perfectly right, it is a bug introduced in https://github.com/tchapi/davis/pull/86. I'm preparing a fix right now

**Comment by tchapi** [comment]
Fixed in https://github.com/tchapi/davis/commit/eed5b480ef69c9c296650f04e6ea2bcb5a0c4489 👌🏼
