### ISSUE TITLE
Publish to docker registry

### ISSUE THREAD

**Issue by tandy-1000** [tchapi/davis#90]
It would be nice to have the docker image published to a docker registry so that it can be pulled easily.

**Comment by tchapi** [comment]
You mean like ... [here](https://github.com/tchapi/davis/pkgs/container/davis) ? 

```
docker pull ghcr.io/tchapi/davis:v3.1.0
```

**Comment by tandy-1000** [comment]
Oh, my bad, I didn't see that in the readme so I thought there wasn't one :)
