### ISSUE TITLE
Custom prefix

### ISSUE THREAD

**Issue by vnghia** [tchapi/davis#97]
Hello,

I would like to ask if we could put the web behind some prefix, for example `prefix/foo/dashboard` ?

Thank you very much !

**Comment by tchapi** [comment]
Hi,

You can tweak your proxy config to do this (Nginx, Caddy, Apache, whatever) - example [here](https://marc.weistroff.net/blog/configuring-nginx-to-serve-a-symfony-project-in-a-subdirectory-of-a-wordpress-website) for instance if I understood your question correctly

**Comment by vnghia** [comment]
I ended up hosting it on a separate subdomain so I did not try your example yet. Thank you very much !
