### ISSUE TITLE
[Crosspost] Have a calender to be subscribable without authentication

### ISSUE THREAD

**Issue by 1Luc1** [tchapi/davis#98]
Hi,

this is basically a [cross-post](https://github.com/sabre-io/Baikal/issues/1189), since I didn't got any answer there :( .
Maybe you ( @tchapi ) some answer?

> Now I'm asking, if there is the possibility that a calender can be accessed and subscribed without login in into the system? Kind of a public calender without login credentials. Within Mozilla Thunderbird there is the option to subscribe to a calender without credentials.

Thanks,
Luc

**Comment by tchapi** [comment]
Hi
There's no possibility at the moment but I'm happy to accept a PR if ever the feature is present in sabre/dav. I guess it looks like it is if I believe https://github.com/sabre-io/dav/pull/820

**Comment by 1Luc1** [comment]
Thanks for the information.
So where does the `{DAV:}unauthorized` belongs to. Is this within a principal within the database?
I'm kind of lost with sabre-io/dav :D .

**Comment by tchapi** [comment]
There's more information in the release notes: https://sabre.io/dav/upgrade/3.1-to-3.2/

**Comment by 1Luc1** [comment]
I did some diggin - and believe me, I'm kind of lost within the sabre/dav legacy code :(.
Anyway I found a place, where adding the following line to SharedCalendar class, method [getACL()]( https://github.com/sabre-io/dav/blob/406f688f040ec5aef04a78b6e525805682bd81f3/lib/CalDAV/SharedCalendar.php#L165) :

```php
 $acl[] = [
    'privilege' => '{DAV:}read',
    'principal' => '{DAV:}unauthenticated',
    'protected' => false,
];
```
... kind of does what I'm looking for. This change will made  _Shared_ calender be subscribe able without loggin in, e.g. from thunderbird.
This will affect all calendars within the installation; this is of course not wanted, so I'm looking for a way, to bind this logic to only selected calendars. @tchapi do you may have some idea, how to achieve this?

**Comment by tchapi** [comment]
Hi again @1Luc1 and thanks for exploring a solution. I'm sorry my latency is high these days (AFK mostly). Will have a look at what you shared and come back to you

**Comment by tchapi** [comment]
I have come up with a solution that _should_ work: see **https://github.com/tchapi/davis/pull/105**

➡️ Would you be able to test, and add your feedback in the draft PR directly, if possible?
