### ISSUE TITLE
LDAP: Bind failed

### ISSUE THREAD

**Issue by markush97** [tchapi/davis#99]
I want to use LDAP-Auth but it is failing with 

```
NOTICE: PHP message: Warning: ldap_bind(): Unable to bind to server: Invalid credentials
```

this error occurs on the moment I open https://ip/dav before even entering any passwords. I install openladp-client inside the container and tried ldapsearch with the provided ldap-uri and it works. My guess is, that it is because the ldap-base is missing. Could you add a way to set this?

Or do you have any other idea why this is happening?

**Comment by tchapi** [comment]
Hi

I'm no LDAP expert, but I know that DN patterns must be precisely crafted for it to work on ldap_bind. See this comment [here](https://github.com/tchapi/davis/issues/55#issuecomment-1066209023) — could that be it?

When you talk about ldap-base, you talk about a PHP package or a Linux package?

**Comment by thelittleblackbird** [comment]
hi all,
how can i add the bind parameters? in my ldap configuration i have disabled the anonymous checks for security reasons but now the user query always fails.

I am using the docker version by the way
regards

**Comment by tchapi** [comment]
Hello @thelittleblackbird 

You can specify params in the `LDAP_*` env params (see [here](https://github.com/tchapi/davis#specific-environment-variables-for-imap-and-ldap-authentication-methods)) — does that answer your question?

**Comment by markush97** [comment]
I would really like to debug this. But I cannot find any logs. Neither in /var/log/* nor in /var/www/davis/var/log*.

Is there a way to increase verbosity? Or where are the php logs being stored to?

**Comment by tchapi** [comment]
> I need some params to make a bind connection with a password. I dont see any other env not even in the code to create such connection.

Having some kind of raw PHP script that you use (and that succeeds in connecting), using the standard php ldap lib, could help me understand what I need to change in the implementation. Would that be possible?

> Neither in /var/log/* nor in /var/www/davis/var/log*.

If you run a server locally you get all the logs in the console directly. In the container, you get all the logs in `/var/www/davis/var/log/prod.log`, but only if you have an error (it's the `fingers_crossed` filter, explained [here](https://symfony.com/doc/current/logging.html#handlers-that-modify-log-entries))

**Comment by thelittleblackbird** [comment]
hi all,

i checked it again and I saw this code in the src/Services/LDAPAuth.php

        try {
            $bind = ldap_bind($ldap, $dn, $password);
            if ($bind) {
                $success = true;
            }
        } catch (\ErrorException $e) {
            error_log($e->getMessage());
            error_log('LDAP Error: '.ldap_error($ldap).' ('.ldap_errno($ldap).')');
        }

This is the snippet of code necessary to launch a bind connection. but dont know how to pass the password to that function.
the other two parameters can be mapped to LDAP_AUTH_URL and LDAP_DN_PATTERN respectively.

so the point is that if i set the $dn to domain name pointing to an user with password (not anonymous connection) then i can not pass the password and therefore the connection fails.

right now with just a variable in the .env for setting the password would be enough (think so)

PS: mi think i said that i couldnt locate the code in charge of the function, but here it is. so clearlyi need to sleep more.

regards

**Comment by tchapi** [comment]
> but dont know how to pass the password to that function.

I don't really understand: the password is the one provided by the user when accessing a resource. If you try in the browser, you will be prompted with an auth dialog box in which you can enter username and password. These are then passed to the `validateUserPass` function of the LDAPAuth service, which in turns calls the `ldapOpen` method.

**Comment by thelittleblackbird** [comment]
hi all,

I spent a bit more time investigating this problem i found that mistake was in my side.

it is working and i am able to sync several profiles counts. So I was totally mistaken.

I have found a problem with the integration with thunderbird and samsung calendar. But this is a totally new history

regards and thanks

**Comment by tchapi** [comment]
Hi @thelittleblackbird 

Glad you had it working ✨ 

> I have found a problem with the integration with thunderbird and samsung calendar

Don't hesitate to open new issues with this if you can, I'll do my best to debug / fix
